### ISSUE TITLE
tfe_registry_module apply fails with resource not found error

### ISSUE THREAD

**Issue by sr-mpamera** [hashicorp/terraform-provider-tfe#381]
Hello

I am trying to create a registry module with below configuration

```
resource "tfe_registry_module" "test" {
  vcs_repo {
    display_identifier = "${local.github_org}/test"
    identifier         = "${local.github_org}/test"
    oauth_token_id     = data.tfe_oauth_client.og-github.oauth_token_id
  }
}
```

#### Expected Behavior
registry_module should be created.

#### Actual Behavior
Error: Error creating registry module from repository org-name/test: resource not found

**Comment by brandonc** [comment]
Hi! Thanks for reporting this. Unfortunately, I'm not able to reproduce this behavior with a straightforward example.

After checking that the oauth client has access to the repository, and you have the appropriate permissions on the org, maybe you can provide a few more details: Are you working against Terraform Cloud or Terraform Enterprise? What version of terraform-provider-tfe are you using?

Thanks!

**Comment by brandonc** [comment]
I'm sorry that I wasn't clear- there are a lot of version numbers in play! Which version of Terraform Enterprise are you using with terraform-provider-tfe 0.24.0? Or are you using it against Terraform Cloud  (app.terraform.io)?

**Comment by datariomj** [comment]
I'm experiencing this as well. For me the its Terraform Cloud (app.terraform.io) and the version is
```
required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.25.3"
    }
  }
```

**Comment by sunaurus** [comment]
I'm having the exact same issue with Terraform Cloud and GitLab (gitlab_hosted).
Notably, trying to create the same module though the Terraform Cloud API succeeds.

So to summarize, the POST request below succeeds and correctly creates the module:

```
POST https://app.terraform.io/api/v2/organizations/<org>/registry-modules/vcs
Authorization: Bearer <token>
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "registry-modules",
    "attributes": {
      "vcs_repo": {
        "identifier": "<org>/<repo>",
        "display_identifier": "<org>/<repo>",
        "oauth-token-id": "<oauth_token_id>"
      }
    }
  }
}
```

However, doing the same through terraform:

```
resource "tfe_registry_module" "test_module" {
  vcs_repo {
    display_identifier = "<org>/<repo>"
    identifier         = "<org>/<repo>"
    oauth_token_id     = tfe_oauth_client.gitlab_client.oauth_token_id
  }
}
```

Results in: `Error: Error creating registry module from repository <org>/<repo>: resource not found`

**Comment by sunaurus** [comment]
`resourceTFERegistryModuleCreate` seems to use `CreateWithVCSConnection` from go-tfe internally.
In `CreateWithVCSConnection`, the POST request is not made to `registry-modules/vcs`, but instead to just `registry-modules`. Could this be the root cause?

https://github.com/hashicorp/go-tfe/blob/df7a2e4fb3a65d212ba136c7eed5c3ebce14bbfe/registry_module.go#L301

**Comment by brandonc** [comment]
@sunaurus Thank you for the detailed notes! I do believe that endpoint is correct because I validated it two ways: With this  config:

```
terraform {
  required_providers {
    tfe = {
      version = "0.25.3"
    }
  }
}

provider "tfe" {
  token    = var.token
}

variable "gh_token" {
  type = string
}

variable "token" {
  type = string
}

resource "tfe_oauth_client" "github_client" {
  organization     = "hashicorp"
  api_url          = "https://api.github.com"
  http_url         = "https://github.com"
  oauth_token      = var.gh_token
  service_provider = "github"
}

resource "tfe_registry_module" "test_module" {
  vcs_repo {
    display_identifier = "brandonc/terraform-aws-simple-s3-cdn"
    identifier         = "brandonc/terraform-aws-simple-s3-cdn"
    oauth_token_id     = tfe_oauth_client.github_client.oauth_token_id
  }
}

output "oauth_id" {
  value = tfe_oauth_client.github_client.oauth_token_id
}
```

And with curl using a payload identical to what the provider sends:

`curl -X POST -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer USER_TOKEN" --data @module.json https://app.terraform.io/api/v2/registry-modules`

where module.json containing:

```
{
  "data": {
    "type": "registry-modules",
    "attributes": {
      "vcs-repo": {
        "identifier": "brandonc/terraform-aws-simple-s3-cdn",
        "oauth-token-id": "ot-YOUR_OAUTH_TOKEN_ID",
        "display-identifier": "brandonc/terraform-aws-simple-s3-cdn",
        "service-provider": "github"
      }
    }
  }
}

```

One difference I see is that so far I've tried reproducing using the github provider instead of gitlab, so I will try that next.

**Comment by sunaurus** [comment]
I tried using `TF_LOG=DEBUG` in my Terraform Cloud workspace and found the failing request/response, here are the logs:
https://gist.github.com/sunaurus/f694e1d7e83d4d4e20edc836b5594396

It's really strange, because when I plug that exact same request into curl (even down to the user agent), the request succeeds, which leads me to believe that this is not even necessarily caused by a bug in the code. 

Would the request be somehow handled differently if it comes from my computer vs when it comes from Terraform Cloud itself? Could there be some different proxies being used or something like that?

**Comment by sunaurus** [comment]
I have now identified my issue, maybe it will help others as well.

In my case, the difference between my failing and successful requests was the API token I was using: it turns out that with the current implementation, **an organization API token can not be used to manage the organization's private registry modules**. Instead, a user needs to provide their own personal API token for the `tfe_registry_module` resource to work.

This seems like a bug to me, though - at the very least, it's very unexpected behaviour.

**Comment by papymaj5** [comment]
I am having the same issue with 0.26.1 using Azure DevOps

**Comment by brandonc** [comment]
@sunaurus Thanks for pointing out the issue you were having. I verified that requests made using org tokens are not allowed to manage registry modules or providers, but this is changing within Terraform Cloud right now and should be corrected in the near future.

**Comment by brandonc** [comment]
@sr-mpamera can you ensure you are using a team/user token to create the module? Are you still experiencing this issue?

**Comment by abstrask** [comment]
I experienced the same. However the token used for the `tfe` provider is being used in several other workspaces, to manage pretty much all other aspects of Terraform Cloud - but still failed on `tfe_registry_module`.

I replaced the *organization* API token with a *team* API token used for the `tfe` provider, which solved my problem.

This is subtly documented in the bottom of this table: https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#access-levels, but there's no mentioning of it on https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/registry_module.

Perhaps it would be a good idea to add a yellow "note" box at the top of the resource documentation? It could have saved me hours and lots of grey hair!
